name: roger_geo_scipy
channels:
    - conda-forge
    - defaults
dependencies:
    # - python=3.6    # Python version 3.6
    # - basemap       # mapping package
    # - bottleneck    # C-optimized array functions for NumPy
    # - cartopy       # Geographic plotting toolkit
    # - cython        # Transpile Python-&gt;C
    # - gpflow        # gaussian processes for machine learning
    # - dask          # Parallel processing library
    # - h5py          # Wrapper for HDF5
    # - ipython       # IPython interpreter and tools
    # - jupyter       # Jupyter federation architecture
    # - jupyterlab    # Jupyter Lab environment
    # - keras-applications        
    # - keras-preprocessing     
    # - matplotlib    # 2D plotting library
    # - netcdf4       # Wrapper for netcdf4
    # - numpy         # N-d array and numerics
    # - pandas        # Labeled array library
    # - proj4         # geographic projections
    # - pyresample    # Geographic resampling tools
    # - scipy         # Common math/stats/science functions
    # - scikit-learn  # Macine learning library
    # - scikit-image  # Image processing routines
    # - statsmodels   # Regression/modeling toolkit
    # - seaborn       # Statistical visualizations
    # - tensorflow     # machine learning
    # - tensorflow-base
    # - _tflow_select
    # - tblib                     
    # - tensorboard              
    # - tqdm          # Nice progress bar for longer computations
    # - xarray        # N-d labeled array library
    # - zarr          # Array storage library
    # - numcodecs     # Compression library used by zarr
    # - gcsfs         # Access data from Google Cloud Storage
    # - s3fs          # Access data from Amazon S3
    # - ffmpeg        # video processing 

    - _tflow_select                          
    - absl-py                                
    - appnope                                
    - asciitree                              
    - asn1crypto                             
    - astor                     
    - atomicwrites              
    - attrs                     
    - backcall                  
    - basemap                   
    - blas                       
    - bleach                    
    - blinker                   
    - bokeh                     
    - boto3                     
    - botocore                  
    - bottleneck                
    - bzip2                     
    - c-ares                    
    - ca-certificates            
    - cachetools             
    - cartopy                   

    - cffi                      
    - cftime                    
    - chardet                     
    - click                       
    - cloudpickle                 
    - configobj                   
    - cryptography                
    - cryptography-vectors        
    - curl                        
    - cycler                      
    - cython                      
    - cytoolz                     
    - dask                        
    - dask-core                   
    - dbus                        
    - decorator                   
    - defusedxml                  
    - distributed                 
    - docutils                    
    - entrypoints                 
    - expat                       
    - fasteners                   
    - ffmpeg                      
    - freetype                    
    - gast                        
    - gcsfs                       
    - geos                        
    - gettext                     
    - glib                        
    - gmp                         
    - gnutls                       
    - google-auth               
    - google-auth-oauthlib         
    - gpflow                      
    - grpcio                      
    - h5py                        
    - hdf4                        
    - hdf5                        
    - heapdict                  
    - icu                         
    - idna                      
    - imageio                   
    - intel-openmp              
    - ipykernel                 
    - ipython                   
    - ipython_genutils          
    - ipywidgets                
    - jedi                                   
    - jinja2                                 
    - jmespath                               
    - jpeg                      
    - jsonschema                             
    - jupyter                                
    - jupyter_client                         
    - jupyter_console           
    - jupyter_core                           
    - jupyterlab                             
    - jupyterlab_server         
    - keras-applications         
    - keras-preprocessing        
    - kiwisolver                 
    - krb5                      
    - libblas
    - libcblas                
    - libcurl                    
    - libcxx                     
    - libcxxabi   
    - libedit                    
    - libffi                     
    - libgfortran               
    - libiconv                   
    - liblapack                 
    - liblapacke               
    - libnetcdf                 
    - libopenblas                
    - libopus                   
    - libpng                    
    - libprotobuf                
    - libsodium                  
    - libssh2                    
    - libtiff                    
    - libvpx                     
    - libxml2                    
    - libxslt                    
    - llvm-meta                         
    - locket                     
    - lxml                       
    - markdown                   
    - markupsafe                 
    - matplotlib                 
    - mistune                    
    - mkl                        
    - mkl_fft                    
    - mkl_random                 
    - mock                       
    - monotonic                  
    - more-itertools           
    - msgpack-python             
    - multipledispatch         
    - nbconvert                  
    - nbformat                   
    - ncurses                    
    - netcdf4                  
    - nettle                    
    - networkx                 
    - nomkl                      
    - notebook             
    - numcodecs                  
    - numpy                      
    - numpy-base                 
    - oauthlib                   
    - olefile                    
    - openblas                    
    - openblas-devel             
    - openh264                    
    - openssl                      
    - owslib                     
    - packaging                  
    - pandas                     
    - pandoc                     
    - pandocfilters              
    - parso                      
    - partd                      
    - patsy                      
    - pbr                        
    - pcre                       
    - pexpect                    
    - pickleshare                
    - pillow                     
    - pip                        
    - pluggy                     
    - proj4                      
    - prometheus_client          
    - prompt_toolkit 
    - protobuf       
    - psutil         
    - ptyprocess     
    - py             
    - pyasn1         
    - pyasn1-modules 
    - pycparser      
    - pyepsg         
    - pygments       
    - pyjwt          
    - pykdtree       
    - pyopenssl      
    - pyparsing      
    - pyproj         
    - pyqt           
    - pyresample                
    - pyrsistent     
    - pyshp          
    - pysocks        
    - pyspharm                
    - pytest         
    - python         
    - python-dateutil          
    - pytz                  
    - pywavelets               
    - pyyaml                
    - pyzmq                    
    - qt                    
    - qtconsole                
    - readline              
    - requests                 
    - requests-oauthlib     
    - rsa                       
    - s3fs                  
    - s3transfer            
    - scikit-image          
    - scikit-learn          
    - scipy                 
    - seaborn               
    - send2trash            
    - setuptools            
    - shapely               
    - sip                   
    - six                   
    - sortedcontainers      
    - sqlite                
    - statsmodels           
    - tblib                 
    - tensorboard           
    - tensorflow              
    - tensorflow-base          
    - termcolor             
    - terminado             
    - testpath              
    - tk                    
    - toolz                 
    - tornado               
    - tqdm                  
    - traitlets             
    - urllib3               
    - wcwidth               
    - webencodings          
    - werkzeug              
    - wheel                 
    - widgetsnbextension    
    - x264                  
    - xarray                
    - xz                    
    - yaml                  
    - zarr                  
    - zeromq                
    - zict                  
    - zlib                  
    - zstd                  
        
