name: roger_geo_scipy
channels:
    - conda-forge
    - defaults
dependencies:
    # - python=3.6    # Python version 3.6
    # - basemap       # mapping package
    # - bottleneck    # C-optimized array functions for NumPy
    # - cartopy       # Geographic plotting toolkit
    # - cython        # Transpile Python-&gt;C
    # - gpflow        # gaussian processes for machine learning
    # - dask          # Parallel processing library
    # - h5py          # Wrapper for HDF5
    # - ipython       # IPython interpreter and tools
    # - jupyter       # Jupyter federation architecture
    # - jupyterlab    # Jupyter Lab environment
    # - keras-applications        
    # - keras-preprocessing     
    # - matplotlib    # 2D plotting library
    # - netcdf4       # Wrapper for netcdf4
    # - numpy         # N-d array and numerics
    # - pandas        # Labeled array library
    # - proj4         # geographic projections
    # - pyresample    # Geographic resampling tools
    # - scipy         # Common math/stats/science functions
    # - scikit-learn  # Macine learning library
    # - scikit-image  # Image processing routines
    # - statsmodels   # Regression/modeling toolkit
    # - seaborn       # Statistical visualizations
    # - tensorflow     # machine learning
    # - tensorflow-base
    # - _tflow_select
    # - tblib                     
    # - tensorboard              
    # - tqdm          # Nice progress bar for longer computations
    # - xarray        # N-d labeled array library
    # - zarr          # Array storage library
    # - numcodecs     # Compression library used by zarr
    # - gcsfs         # Access data from Google Cloud Storage
    # - s3fs          # Access data from Amazon S3
    # - ffmpeg        # video processing 

    - _tflow_select             2.3.0                       mkl  
    - absl-py                   0.7.0                    py36_0  
    - appnope                   0.1.0            py36hf537a9a_0  
    - asciitree                 0.3.3                      py_2  
    - asn1crypto                0.24.0                   py36_0  
    - astor                     0.7.1                    py36_0  
    - atomicwrites              1.3.0                      py_0  
    - attrs                     19.1.0                     py_0  
    - backcall                  0.1.0                    py36_0  
    - basemap                   1.2.0            py36h0acbc05_0  
    - blas                      2.4                    openblas    conda-forge
    - bleach                    3.1.0                    py36_0  
    - blinker                   1.4                      py36_0  
    - bokeh                     1.0.4                    py36_0  
    - boto3                     1.9.111                    py_0  
    - botocore                  1.12.112                   py_0  
    - bottleneck                1.2.1            py36h1d22016_1  
    - bzip2                     1.0.6                h1de35cc_5  
    - c-ares                    1.15.0               h1de35cc_1  
    - ca-certificates           2019.3.9             hecc5488_0    conda-forge
    - cachetools                2.1.0                      py_0    conda-forge
    - cartopy                   0.16.0           py36h9263bd1_0  
    - certifi                   2019.3.9                 py36_0    conda-forge
    - cffi                      1.12.2           py36hb5b8e2f_1  
    - cftime                    1.0.3.4          py36h1d22016_0  
    - chardet                   3.0.4                    py36_1  
    - click                     7.0                      py36_0  
    - cloudpickle               0.8.0                    py36_0  
    - configobj                 5.0.6                    py36_1  
    - cryptography              2.6.1            py36ha12b0ac_0  
    - cryptography-vectors      2.6.1                      py_0  
    - curl                      7.64.0               ha441bb4_2  
    - cycler                    0.10.0           py36hfc81398_0  
    - cython                    0.29.6           py36h0a44026_0  
    - cytoolz                   0.9.0.1          py36h1de35cc_1  
    - dask                      1.1.4                      py_0  
    - dask-core                 1.1.4                      py_0  
    - dbus                      1.13.6               h90a0687_0  
    - decorator                 4.3.2                    py36_0  
    - defusedxml                0.5.0                    py36_1  
    - distributed               1.26.0                   py36_1  
    - docutils                  0.14             py36hbfde631_0  
    - entrypoints               0.3                      py36_0  
    - expat                     2.2.6                h0a44026_0  
    - fasteners                 0.14.1                     py_3  
    - ffmpeg                    4.0                  h01ea3c9_0  
    - freetype                  2.9.1                hb4e5f40_0  
    - gast                      0.2.2                    py36_0  
    - gcsfs                     0.2.0                      py_0    conda-forge
    - geos                      3.6.2                h5470d99_2  
    - gettext                   0.19.8.1             h15daf44_3  
    - glib                      2.56.2               hd9629dc_0  
    - gmp                       6.1.2                hb37e062_1  
    - gnutls                    3.5.19               h2a4e5f8_1    conda-forge
    - google-auth               1.6.1                      py_0    conda-forge
    - google-auth-oauthlib      0.2.0                 py36_1000    conda-forge
    - gpflow                    1.3.0                    py36_0    conda-forge
    - grpcio                    1.16.1           py36h044775b_1  
    - h5py                      2.9.0            py36h3134771_0  
    - hdf4                      4.2.13               h39711bb_2  
    - hdf5                      1.10.4               hfa1e0ec_0  
    - heapdict                  1.0.0                    py36_2  
    - icu                       58.2                 h4b95b61_1  
    - idna                      2.8                      py36_0  
    - imageio                   2.5.0                    py36_0  
    - intel-openmp              2019.1                      144  
    - ipykernel                 5.1.0            py36h39e3cac_0  
    - ipython                   7.3.0            py36h39e3cac_0  
    - ipython_genutils          0.2.0            py36h241746c_0  
    - ipywidgets                7.4.2                    py36_0  
    - jedi                      0.13.3                   py36_0  
    - jinja2                    2.10                     py36_0  
    - jmespath                  0.9.4                      py_0  
    - jpeg                      9b                   he5867d9_2  
    - jsonschema                3.0.1                    py36_0  
    - jupyter                   1.0.0                    py36_7  
    - jupyter_client            5.2.4                    py36_0  
    - jupyter_console           6.0.0                    py36_0  
    - jupyter_core              4.4.0                    py36_0  
    - jupyterlab                0.35.4           py36hf63ae98_0  
    - jupyterlab_server         0.2.0                    py36_0  
    - keras-applications        1.0.7                      py_0  
    - keras-preprocessing       1.0.9                      py_0  
    - kiwisolver                1.0.1            py36h0a44026_0  
    - krb5                      1.16.1               hddcf347_7  
    - libblas                   3.8.0                4_openblas    conda-forge
    - libcblas                  3.8.0                4_openblas    conda-forge
    - libcurl                   7.64.0               h051b688_2  
    - libcxx                    4.0.1                hcfea43d_1  
    - libcxxabi                 4.0.1                hcfea43d_1  
    - libedit                   3.1.20181209         hb402a30_0  
    - libffi                    3.2.1                h475c297_4  
    - libgfortran               3.0.1                h93005f0_2  
    - libiconv                  1.15                 hdd342a3_7  
    - liblapack                 3.8.0                4_openblas    conda-forge
    - liblapacke                3.8.0                4_openblas    conda-forge
    - libnetcdf                 4.6.1                hd5207e6_2  
    - libopenblas               0.3.3                hdc02c5d_3  
    - libopus                   1.3                  h1de35cc_0  
    - libpng                    1.6.36               ha441bb4_0  
    - libprotobuf               3.6.1                hd9629dc_0  
    - libsodium                 1.0.16               h3efe00b_0  
    - libssh2                   1.8.0                ha12b0ac_4  
    - libtiff                   4.0.10               hcb84e12_2  
    - libvpx                    1.7.0                h378b8a2_0  
    - libxml2                   2.9.9                hab757c2_0  
    - libxslt                   1.1.33               h33a18ac_0  
    - llvm-meta                 7.0.0                         0    conda-forge
    - locket                    0.2.0            py36hca03003_1  
    - lxml                      4.3.2            py36hef8c89e_0  
    - markdown                  3.0.1                    py36_0  
    - markupsafe                1.1.1            py36h1de35cc_0  
    - matplotlib                3.0.3            py36h54f8f79_0  
    - mistune                   0.8.4            py36h1de35cc_0  
    - mkl                       2019.1                      144  
    - mkl_fft                   1.0.1            py36h917ab60_0  
    - mkl_random                1.0.1            py36h78cc56f_0  
    - mock                      2.0.0            py36hd48142b_0  
    - monotonic                 1.5                        py_0  
    - more-itertools            6.0.0                    py36_0  
    - msgpack-python            0.6.1            py36h04f5b5a_1  
    - multipledispatch          0.6.0                    py36_0  
    - nbconvert                 5.4.1                      py_2  
    - nbformat                  4.4.0            py36h827af21_0  
    - ncurses                   6.1                  h0a44026_1  
    - netcdf4                   1.4.2            py36h13743db_0  
    - nettle                    3.3                           0    conda-forge
    - networkx                  2.2                      py36_1  
    - nomkl                     3.0                           0  
    - notebook                  5.7.6                    py36_0  
    - numcodecs                 0.5.4            py36h0a44026_0  
    - numpy                     1.16.2           py36h926163e_0  
    - numpy-base                1.16.2           py36ha711998_0  
    - oauthlib                  3.0.1                      py_0  
    - olefile                   0.46                     py36_0  
    - openblas                  0.3.5             h436c29b_1001    conda-forge
    - openblas-devel            0.3.3                         3  
    - openh264                  1.8.0                hd28b015_0    conda-forge
    - openssl                   1.1.1b               h01d97ff_2    conda-forge
    - owslib                    0.17.1                     py_0  
    - packaging                 19.0                     py36_0  
    - pandas                    0.24.2           py36h0a44026_0  
    - pandoc                    2.2.3.2                       0  
    - pandocfilters             1.4.2                    py36_1  
    - parso                     0.3.4                    py36_0  
    - partd                     0.3.9                    py36_0  
    - patsy                     0.5.1                    py36_0  
    - pbr                       5.1.3                      py_0  
    - pcre                      8.43                 h0a44026_0  
    - pexpect                   4.6.0                    py36_0  
    - pickleshare               0.7.5                    py36_0  
    - pillow                    5.4.1            py36hb68e598_0  
    - pip                       19.0.3                   py36_0  
    - pluggy                    0.9.0                    py36_0  
    - proj4                     5.0.1                h1de35cc_0  
    - prometheus_client         0.6.0                    py36_0  
    - prompt_toolkit            2.0.9                    py36_0  
    - protobuf                  3.6.1            py36h0a44026_0  
    - psutil                    5.6.1            py36h1de35cc_0  
    - ptyprocess                0.6.0                    py36_0  
    - py                        1.8.0                    py36_0  
    - pyasn1                    0.4.5                      py_0  
    - pyasn1-modules            0.2.4                    py36_0  
    - pycparser                 2.19                     py36_0  
    - pyepsg                    0.4.0                    py36_0  
    - pygments                  2.3.1                    py36_0  
    - pyjwt                     1.7.1                    py36_0  
    - pykdtree                  1.3.1            py36h1d22016_2  
    - pyopenssl                 19.0.0                   py36_0  
    - pyparsing                 2.3.1                    py36_0  
    - pyproj                    1.9.5.1          py36h833a5d7_1  
    - pyqt                      5.9.2            py36h655552a_2  
    - pyresample                1.10.3           py36hf8a1672_0    conda-forge
    - pyrsistent                0.14.11          py36h1de35cc_0  
    - pyshp                     2.0.1                    py36_0  
    - pysocks                   1.6.8                    py36_0  
    - pyspharm                  1.0.9           py36hfa2f21f_1003    conda-forge
    - pytest                    4.3.0                    py36_0  
    - python                    3.6.8                haf84260_0  
    - python-dateutil           2.8.0                    py36_0  
    - pytz                      2018.9                   py36_0  
    - pywavelets                1.0.2            py36h1d22016_0  
    - pyyaml                    3.13             py36h1de35cc_0  
    - pyzmq                     18.0.0           py36h0a44026_0  
    - qt                        5.9.7                h468cd18_1  
    - qtconsole                 4.4.3                    py36_0  
    - readline                  7.0                  h1de35cc_5  
    - requests                  2.21.0                   py36_0  
    - requests-oauthlib         1.2.0                      py_0  
    - rsa                       3.4.2                      py_1    conda-forge
    - s3fs                      0.2.0                    py36_0  
    - s3transfer                0.2.0                    py36_0  
    - scikit-image              0.14.2           py36h0a44026_0  
    - scikit-learn              0.20.3           py36hebd9d1a_0  
    - scipy                     1.2.1            py36h1a1e112_0  
    - seaborn                   0.9.0                    py36_0  
    - send2trash                1.5.0                    py36_0  
    - setuptools                40.8.0                   py36_0  
    - shapely                   1.6.4            py36h20de77a_0  
    - sip                       4.19.8           py36h0a44026_0  
    - six                       1.12.0                   py36_0  
    - sortedcontainers          2.1.0                    py36_0  
    - sqlite                    3.27.2               ha441bb4_0  
    - statsmodels               0.9.0            py36h1d22016_0  
    - tblib                     1.3.2            py36hda67792_0  
    - tensorboard               1.12.2           py36haf313ee_0  
    - tensorflow                1.12.0          mkl_py36h2b2bbaf_0  
    - tensorflow-base           1.12.0          mkl_py36h70e0e9a_0  
    - termcolor                 1.1.0                    py36_1  
    - terminado                 0.8.1                    py36_1  
    - testpath                  0.4.2                    py36_0  
    - tk                        8.6.8                ha441bb4_0  
    - toolz                     0.9.0                    py36_0  
    - tornado                   6.0.1            py36h1de35cc_0  
    - tqdm                      4.31.1                     py_0  
    - traitlets                 4.3.2            py36h65bd3ce_0  
    - urllib3                   1.24.1                   py36_0  
    - wcwidth                   0.1.7            py36h8c6ec74_0  
    - webencodings              0.5.1                    py36_1  
    - werkzeug                  0.14.1                   py36_0  
    - wheel                     0.33.1                   py36_0  
    - widgetsnbextension        3.4.2                    py36_0  
    - x264                      1!152.20180717       h470a237_1    conda-forge
    - xarray                    0.11.3                   py36_0  
    - xz                        5.2.4                h1de35cc_4  
    - yaml                      0.1.7                hc338f04_2  
    - zarr                      2.2.0                      py_0  
    - zeromq                    4.3.1                h0a44026_3  
    - zict                      0.1.4                    py36_0  
    - zlib                      1.2.11               h1de35cc_3  
    - zstd                      1.3.7                h5bba6e5_0  
        
